name: Basic Tests
on: [push, pull_request]
jobs:
  build:
    name: Build & Run Basic Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -Dtest=on
          make
      - name: Run
        run: |
          cd build/test
          ./LightestCoreTest -r0 && ./LightestDataAnalysisExtTest -r0 && ./LightestAsyncTestExtTest
